import type { JobAnalyticsDetail } from "@/types/analytics";

const fixturePayload = {
  contractVersion: "analytics-job-detail-v1",
  job: {
    id: "job-google-backend-pilot",
    title: "Senior Back-end Developer",
    guild: "Engineering",
    status: "active",
    createdAt: "2026-04-01T00:00:00.000Z",
  },
  summary: {
    totalCandidates: 12,
    endorsedCandidates: 4,
    vettedOnlyCandidates: 5,
    rejectedCandidates: 3,
    acceptedCandidates: 0,
    trackedHireOutcomes: 2,
    requiredHireOutcomes: 5,
    prescriptiveUnlocked: false,
  },
  candidates: [
    {
      id: "proposal-ronan-webb",
      source: "proposal",
      applicationId: "application-ronan-webb",
      guildApplicationId: "guild-application-ronan-webb",
      proposalId: "proposal-ronan-webb",
      candidateId: "candidate-ronan-webb",
      name: "Ronan Webb",
      headline: "Backend systems engineer",
      appliedAt: "2026-04-24T09:00:00.000Z",
      applicationStatus: "reviewing",
      analyticsStatus: "endorsed",
      vettingScore: 92,
      scoreStatus: "scored",
      consensus: {
        finalScore: 92,
        state: "finalized",
        algorithmVersion: "iqr-v1",
        minReviewsRequired: 3,
        completedReviews: 3,
        tiebreakerRequired: false,
        finalizedAt: "2026-04-27T09:00:00.000Z",
      },
      reviewerCount: 3,
      selectedEndorserCount: 3,
      selectedEndorsementAmount: "2150",
      totalBidAmount: "2900",
      criteriaScores: [
        { criterionId: "technical_depth", label: "Technical depth", averageScore: 19, maxScore: 20, scoreStatus: "scored", source: "fixture" },
        { criterionId: "systems_judgment", label: "Systems judgment", averageScore: 18, maxScore: 20, scoreStatus: "scored", source: "fixture" },
        { criterionId: "ownership", label: "Ownership", averageScore: 19, maxScore: 20, scoreStatus: "scored", source: "fixture" },
        { criterionId: "communication", label: "Communication", averageScore: 17, maxScore: 20, scoreStatus: "scored", source: "fixture" },
      ],
      reviews: [
        {
          reviewId: "vote-dave-ronan",
          source: "proposal_vote",
          expertId: "expert-dave",
          publicName: "Dave Mustaine",
          score: 93,
          vote: "for",
          contributedToConsensus: true,
          alignmentState: "included",
          alignmentDistance: 1,
          slashingTier: "aligned",
          feedback: "Great technical depth. Would definitely hire.",
          criteriaScores: [{ criterionId: "technical_depth", label: "Technical depth", score: 19, maxScore: 20, evidence: "Strong systems examples." }],
          createdAt: "2026-04-26T10:00:00.000Z",
        },
        {
          reviewId: "vote-john-ronan",
          source: "proposal_vote",
          expertId: "expert-john",
          publicName: "John Wick",
          score: 92,
          vote: "for",
          contributedToConsensus: true,
          alignmentState: "included",
          alignmentDistance: 0,
          slashingTier: "aligned",
          feedback: "Strong distributed systems intuition. Clear architecture choices, no over-engineering.",
          criteriaScores: [{ criterionId: "systems_judgment", label: "Systems judgment", score: 18, maxScore: 20, evidence: "Clean tradeoffs." }],
          createdAt: "2026-04-26T10:30:00.000Z",
        },
        {
          reviewId: "vote-corey-ronan",
          source: "proposal_vote",
          expertId: "expert-corey",
          publicName: "Corey Taylor",
          score: 79,
          vote: "for",
          contributedToConsensus: false,
          alignmentState: "dissenting",
          alignmentDistance: 13,
          slashingTier: "moderate_deviation",
          feedback: "Solid answers, but not as strong on communication under ambiguity.",
          criteriaScores: null,
          createdAt: "2026-04-26T11:00:00.000Z",
        },
      ],
      bids: [
        { bidId: "bid-dave-ronan", expertId: "expert-dave", publicName: "Dave M.", amount: "800", refundAmount: "0", rank: 1, outcome: "selected", placedAt: "2026-04-27T10:00:00.000Z" },
        { bidId: "bid-jimmy-ronan", expertId: "expert-jimmy", publicName: "Jimmy P.", amount: "750", refundAmount: "0", rank: 2, outcome: "selected", placedAt: "2026-04-27T10:10:00.000Z" },
        { bidId: "bid-jimi-ronan", expertId: "expert-jimi", publicName: "Jimi H.", amount: "600", refundAmount: "0", rank: 3, outcome: "selected", placedAt: "2026-04-27T10:20:00.000Z" },
        { bidId: "bid-corey-ronan", expertId: "expert-corey", publicName: "Corey T.", amount: "300", refundAmount: "300", rank: 5, outcome: "returned", placedAt: "2026-04-27T11:00:00.000Z" },
      ],
    },
    {
      id: "proposal-jonas-lee",
      source: "proposal",
      applicationId: null,
      guildApplicationId: "guild-application-jonas-lee",
      proposalId: "proposal-jonas-lee",
      candidateId: "candidate-jonas-lee",
      name: "Jonas Lee",
      headline: "API architecture",
      appliedAt: null,
      applicationStatus: null,
      analyticsStatus: "reviewing",
      vettingScore: null,
      scoreStatus: "insufficient_reviews",
      consensus: {
        finalScore: null,
        state: "in_progress",
        algorithmVersion: null,
        minReviewsRequired: 3,
        completedReviews: 1,
        tiebreakerRequired: false,
        finalizedAt: null,
      },
      reviewerCount: 1,
      selectedEndorserCount: 0,
      selectedEndorsementAmount: "0",
      totalBidAmount: "0",
      criteriaScores: [],
      reviews: [],
      bids: [],
    },
  ],
  insights: {
    criteriaAverages: [
      { criterionId: "technical_depth", label: "Technical depth", averageScore: 18.6, maxScore: 20, candidateCount: 8 },
      { criterionId: "systems_judgment", label: "Systems judgment", averageScore: 17.2, maxScore: 20, candidateCount: 8 },
      { criterionId: "ownership", label: "Ownership", averageScore: 17.7, maxScore: 20, candidateCount: 8 },
      { criterionId: "communication", label: "Communication", averageScore: 14.8, maxScore: 20, candidateCount: 8 },
    ],
    criteriaDistributions: [
      {
        criterionId: "technical_depth",
        label: "Technical depth",
        buckets: [
          { label: "0–4", count: 0 },
          { label: "5–9", count: 0 },
          { label: "10–14", count: 1 },
          { label: "15–19", count: 7 },
          { label: "20", count: 0 },
        ],
      },
      {
        criterionId: "systems_judgment",
        label: "Systems judgment",
        buckets: [
          { label: "0–4", count: 0 },
          { label: "5–9", count: 1 },
          { label: "10–14", count: 2 },
          { label: "15–19", count: 5 },
          { label: "20", count: 0 },
        ],
      },
      {
        criterionId: "ownership",
        label: "Ownership",
        buckets: [
          { label: "0–4", count: 0 },
          { label: "5–9", count: 1 },
          { label: "10–14", count: 1 },
          { label: "15–19", count: 5 },
          { label: "20", count: 1 },
        ],
      },
      {
        criterionId: "communication",
        label: "Communication",
        buckets: [
          { label: "0–4", count: 1 },
          { label: "5–9", count: 2 },
          { label: "10–14", count: 3 },
          { label: "15–19", count: 2 },
          { label: "20", count: 0 },
        ],
      },
    ],
    endorsementCorrelation: {
      status: "available",
      message: null,
      items: [
        { criterionId: "technical_depth", label: "Technical depth", correlation: 0.72 },
        { criterionId: "ownership", label: "Ownership", correlation: 0.61 },
        { criterionId: "systems_judgment", label: "Systems judgment", correlation: 0.48 },
        { criterionId: "communication", label: "Communication", correlation: -0.18 },
      ],
    },
    disagreement: {
      status: "available",
      flags: [{
        candidateRowId: "proposal-ronan-webb",
        candidateId: "candidate-ronan-webb",
        candidateName: "Ronan Webb",
        message: "Candidate has one dissenting expert score.",
        severity: "medium",
      }],
    },
    outcomeReadiness: {
      requiredHireOutcomes: 5,
      trackedHireOutcomes: 2,
      unlocked: false,
    },
  },
} satisfies JobAnalyticsDetail;

export const jobAnalyticsFixture = fixturePayload;
